// Report house style. Mirrors the ```config``` block in ../../design-system.md, which
// remains the human-facing source of truth. Keep these values in sync with that file.

export interface DesignConfig {
  title_format: string;
  disclaimer: string;
  citation_note: string;
  sections: string[];
  tone: string;
}

export const DESIGN: DesignConfig = {
  title_format: "{company} {quarter} Earnings Call Analysis",
  disclaimer:
    "Generated by the Earnings-Call Analyzer for demonstration. Hypotheses offered for " +
    "correction, not investment advice. In production this runs on approved infrastructure " +
    "with data governance and model-risk review. The personal API key is demo-only.",
  citation_note:
    "Every figure and material claim cites its source line as [Ln]. Uncited claims are flagged, not hidden.",
  sections: [
    "executive_summary",
    "guidance",
    "key_metrics",
    "management_tone",
    "risks",
    "qa_highlights",
    "notable_quotes",
  ],
  tone: "institutional, measured, hypotheses-not-verdicts",
};

export const SECTION_TITLES: Record<string, string> = {
  executive_summary: "Executive Summary",
  guidance: "Guidance & Outlook",
  key_metrics: "Key Metrics",
  management_tone: "Management Tone",
  risks: "Risks & Headwinds",
  qa_highlights: "Q&A Highlights",
  notable_quotes: "Notable Quotes",
};
